// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEQwO8F-kN2bZV6a_lSh2tqh8IoXTBhZ8',
    appId: '1:1695891393:web:895ba977dc7fe5bed3f940',
    messagingSenderId: '1695891393',
    projectId: 'cheapestitemninja',
    authDomain: 'cheapestitemninja.firebaseapp.com',
    storageBucket: 'cheapestitemninja.appspot.com',
    measurementId: 'G-V2Z40K4M22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjxsV077ybCgHZEb-J7n56Fj0BvYM7mUI',
    appId: '1:1695891393:android:2f437844785b0c5ad3f940',
    messagingSenderId: '1695891393',
    projectId: 'cheapestitemninja',
    storageBucket: 'cheapestitemninja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-P6OTtkjFUqWigZVUcwSLVYQ-KAWWsk',
    appId: '1:1695891393:ios:d0e6d6a1e06c2efcd3f940',
    messagingSenderId: '1695891393',
    projectId: 'cheapestitemninja',
    storageBucket: 'cheapestitemninja.appspot.com',
    iosBundleId: 'com.example.cheapestItemNinja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-P6OTtkjFUqWigZVUcwSLVYQ-KAWWsk',
    appId: '1:1695891393:ios:874b050c44373e45d3f940',
    messagingSenderId: '1695891393',
    projectId: 'cheapestitemninja',
    storageBucket: 'cheapestitemninja.appspot.com',
    iosBundleId: 'com.example.cheapestItemNinja.RunnerTests',
  );
}
